#!/sbin/sh

sed -i 's,hw.cameras=1,hw.cameras=2,g' /system/build.prop
sed -i 's,#ro.sf.gsensorposition=2,ro.sf.gsensorposition=1,g' /system/build.prop
sed -i 's,ro.sf.gsensorposition=2,ro.sf.gsensorposition=4,g' /system/build.prop
sed -i 's,ro.sys.max_cpu_on=1320000,ro.sys.max_cpu_on=1200000,g' /system/build.prop
sed -i 's,ro.vout.dualdisplay2=true,ro.vout.dualdisplay2=false,g' /system/build.prop
sed -i 's,ro.vout.dualdisplay3=false,ro.vout.dualdisplay3=true,g' /system/build.prop
sed -i 's,ro.sf.lcd_density=160,ro.sf.lcd_density=213,g' /system/build.prop
echo "ro.camera.orientation.front=90" >> /system/build.prop
echo "ro.camera.orientation.back=270" >> /system/build.prop
#echo "bma250.sf.gsensorposition=6" >> /system/build.prop
#echo "mma8452.sf.gsensorposition=5" >> /system/build.prop
#echo "rw.sensors.gsensor.installdir=1100" >> /system/build.prop
echo "ro.real_device=Gadmei E8-3D" >> /system/build.prop
sed -i 's persist.sys.usb.config=mtp persist.sys.usb.config=adb g' /system/build.prop

echo "# support 3d apk" >> /system/build.prop
echo "ro.product.build.support3d=true" >> /system/build.prop
echo "# For TriDef 3D Games" >> /system/build.prop
echo "ro.product.build.dim=E83D-T380-GADMEIUS-NEO3DO_GADMEIUS-NEO3DO_V1.0.1.20131214" >> /system/build.prop

if grep ro.omni.device /system/build.prop ; then
  # OmniRom detected
  mv /system/media/bootanimation_omni.zip /system/media/bootanimation.zip
  rm /system/media/bootanimation_cm.zip
fi

if grep ro.cm.device /system/build.prop ; then
  # CyanogenMod detected
  mv /system/media/bootanimation_cm.zip /system/media/bootanimation.zip
  rm /system/media/bootanimation_omni.zip
  rm /system/app/Torch.apk # Does not work anyway
fi
rm /system/app/VideoPlayer.apk # Does not work anyway
rm /system/etc/wifi/40181 # Unneeded

# Localization
sed -i 's persist.sys.timezone=Europe/Rome persist.sys.timezone=Europe/Moscow g' /system/build.prop
sed -i 's persist.sys.language=en persist.sys.language=ru g' /system/build.prop
sed -i 's persist.sys.country=US persist.sys.country=RU g' /system/build.prop

