#!/sbin/sh
set_prop(){
  name="$1"
  value="$2"
  file="/system/build.prop"
  if grep -q "^$name=" "$file"; then
    #echo "$name is exist in $file"
    sed -i "s#^$name=.*#$name=$value#g" "$file"
  else
    #echo "$name is not exist in $file"
    echo "$name=$value" >> "$file"
  fi
}

set_prop hw.cameras 2
set_prop ro.sys.max_cpu_on 1200000
set_prop ro.vout.dualdisplay2 false
set_prop ro.vout.dualdisplay3 true
set_prop ro.real_device "Gadmei E8-3D"
set_prop persist.sys.usb.config adb

# For correct rotation
set_prop ro.sf.hwrotation 270
set_prop ro.sf.gsensorposition 3
set_prop ro.camera.orientation.front 0
set_prop ro.camera.orientation.back 0

set_prop rw.youtube_workaround 0 # Fixes video streaming in 3DPlayer and/or Yabazam 3D
set_prop ro.product.build.support3d true # For 3DPlayer and 3DImageView
set_prop ro.product.build.dim E83D-T380-GADMEIUS-NEO3DO_GADMEIUS-NEO3DO_V1.0.1.20131214 # For TriDef 3D Games
set_prop ro.product.manufacturer Gadmei # For Phereo photo viewer

rm /system/app/VideoPlayer.apk # 3DPlayer is better
rm -r /system/etc/wifi/40181 # Unneeded

if grep -q ^ro.omni.device /system/build.prop ; then
  # OmniRom detected
  mv /system/lib/libinputservice.so /system/lib/libinputservice_ORIG.so
  cp /system/lib/libinputservice_OMNI_4.4.4_PATCHED.so /system/lib/libinputservice.so
  rm /system/lib/libinputservice_CM11_4.4.4_PATCHED.so
fi

if grep -q ^ro.cm.device /system/build.prop ; then
  # CyanogenMod detected
  rm /system/app/Torch.apk # Does not work anyway
  mv /system/lib/libinputservice.so /system/lib/libinputservice_ORIG.so
  cp /system/lib/libinputservice_CM11_4.4.4_PATCHED.so /system/lib/libinputservice.so
  rm /system/lib/libinputservice_OMNI_4.4.4_PATCHED.so
fi


# WLAN drivers are little messy
if [ "`getprop sys.uses.ext4`" = "1" ]; then
  # EXT4 system
  rm /system/lib/modules/dhd_ubifs.ko
  mv /system/lib/modules/dhd_ext4.ko /system/lib/modules/dhd.ko
  mv /system/etc/wifi_ext4/* /system/etc/wifi/
else
  # UBIFS system
  rm /system/lib/modules/dhd_ext4.ko
  mv /system/lib/modules/dhd_ubifs.ko /system/lib/modules/dhd.ko
  mv /system/etc/wifi_ubifs/* /system/etc/wifi/
fi
rm -r /system/etc/wifi_ubifs /system/etc/wifi_ext4

# Localization
set_prop persist.sys.timezone Europe/Moscow
set_prop persist.sys.language ru
set_prop persist.sys.country RU
