#!/system/bin/sh
#

# ext4
#insmod /system/lib/modules/jbd2.ko
#insmod /system/lib/modules/ext4.ko

# network
insmod /system/lib/modules/tun.ko
insmod /system/lib/modules/tcp_veno.ko
echo veno > /proc/sys/net/ipv4/tcp_congestion_control

# usb serial
insmod /system/lib/modules/cp210x.ko
insmod /system/lib/modules/pl2303.ko

# gamepads
insmod /system/lib/modules/xpad.ko
insmod /system/lib/modules/hid-gaff.ko
insmod /system/lib/modules/hid-pl.ko
insmod /system/lib/modules/hid-sony.ko

# misc
insmod /system/lib/modules/uinput.ko
#insmod /system/lib/modules/cifs.ko

# usb audio
insmod /system/lib/modules/snd-hwdep.ko
insmod /system/lib/modules/snd-rawmidi.ko
insmod /system/lib/modules/snd-usbmidi-lib.ko
insmod /system/lib/modules/snd-usb-audio.ko
